version: "3.8"

services:
  aiogram:
    build: ./telegram_bot
    restart: always
    environment:
      - ENV_FILE=${ENV_FILE:-.env}
    volumes:
      - ./${ENV_FILE:-.env}/:/app/${ENV_FILE:-.env}/:ro
      - ./telegram_bot/logs/:/app/logs/:rw
    depends_on:
      - postgres
      - redis
      - selenium

  postgres:
    image: postgres
    restart: always
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_idv2:/var/lib/postgresql/data/pgdata/idiotDiaryV2
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/idiotDiaryV2

  redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command:
      - "redis-server"
      - "--loglevel ${REDIS_LOGLEVEL:-warning}"
      - "--databases 2"
      - "--save 900 1"
      - "--save 300 10"
      - "--save 60 10000"
      - "--maxmemory ${REDIS_MAXMEM:-50mb}"
      - "--maxmemory-policy ${REDIS_POLICY:-noeviction}"
      - "--requirepass ${REDIS_PASS}"
    volumes:
      - redis:/data
    env_file:
      - ${ENV_FILE:-.env}

  nginx:
    image: nginx
    restart: always
    ports:
      - "${WEBHOOK_PORT:-443}:443"
      - "8444:80"
    volumes:
      - ${CERTS_DIR:-./}:/data/certs/:ro
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template/:rw
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - aiogram

  selenium:
    image: selenium/standalone-chrome:latest
    restart: always
    shm_size: 500m
    ports:
      - "${SELENIUM_PORT}:${SELENIUM_PORT}"
      - "7900:7900"
    privileged: true

volumes:
  redis:
  pg_idv2: