version: "3"

services:
  aiogram:
    build: ./telegram_bot
    restart: always
    volumes:
      - ./.env/:/app/.env/:ro
    network_mode: host
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    network_mode: host
    env_file:
      - ./.env
    ports:
      - '6432:5432'
    volumes:
      - pg_idv2:/var/lib/postgresql/data/pgdata/idiotDiaryV2
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/idiotDiaryV2

  redis:
    image: redis
    restart: always
    network_mode: host
    ports:
      - '6379:6379'
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass ${REDIS_PASS}'
    volumes:
      - redis:/data
    env_file:
      - ./.env

  nginx:
    image: nginx
    restart: always
    network_mode: host
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ~/certs-data/certs/:/data/certs/:ro
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template/:rw
    env_file:
      - ./.env
    depends_on:
      - aiogram


volumes:
  redis:
  pg_idv2: