services:

  #####  SERVICES  #####

  aiogram:
    build: .
    ports:
      - "127.0.0.1:${EXPOSE_API:-8000}:8000"
    volumes:
      - type: "bind"
        source: "./log/"
        target: "/app/log/"
      - type: "bind"
        source: "./temp/"
        target: "/app/temp/"
      - type: "bind"
        source: "./config/"
        target: "/app/config/"
        read_only: true
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - migrations
    restart: always
    entrypoint:
      [ "poetry", "run", "python", "-m", "idiotDiary" ]
    profiles:
      - services

  taskiq:
    build: .
    restart: always
    volumes:
      - type: "bind"
        source: "./temp/"
        target: "/app/temp/"
      - type: "bind"
        source: "./config/"
        target: "/app/config/"
        read_only: true
      - type: "bind"
        source: "./cookies/"
        target: "/app/cookies/"
    depends_on:
      - rabbitmq
      - selenium
      - postgres
      - redis
      - migrations
    entrypoint:
      [ "poetry", "run", "taskiq", "worker", "--tasks-pattern", "['**/tasks']", "idiotDiary.mq.run:broker" ]
    profiles:
      - services

  #####  RUNNERS  #####

  postgres:
    image: postgres
    restart: always
    env_file:
      - ${DOCKER_ENV_FILE:-.env}
    ports:
      - "127.0.0.1:${EXPOSE_PG:-5432}:5432"
    volumes:
      - type: "volume"
        source: "postgres"
        target: "/app/pgdata/idiotDiary/"
    environment:
      PGDATA: /app/pgdata/idiotDiary/
    profiles:
      - runners

  redis:
    image: redis
    restart: always
    ports:
      - "127.0.0.1:${EXPOSE_REDIS:-6379}:6379"
    volumes:
      - type: "volume"
        source: "redis"
        target: "/data/"
    env_file:
      - ${DOCKER_ENV_FILE:-.env}
    command:
      - "redis-server"
      - "--loglevel ${REDIS_LOGLEVEL:-warning}"
      - "--databases 2"
      - "--save 900 1"
      - "--save 300 10"
      - "--save 60 10000"
      - "--maxmemory ${REDIS_MAXMEM:-50mb}"
      - "--maxmemory-policy ${REDIS_POLICY:-noeviction}"
      - "--requirepass ${REDIS_PASSWORD}"
    profiles:
      - runners

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "127.0.0.1:${EXPOSE_RABBITMQ}:5672"
      - "127.0.0.1:${EXPOSE_RABBITMQ_HTTP}:15672"
    volumes:
      - type: "volume"
        source: "rabbitmq"
        target: "/var/lib/rabbitmq/"
    env_file:
      - ${DOCKER_ENV_FILE:-.env}
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    profiles:
      - runners

  selenium:
    image: selenium/standalone-chrome:latest
    restart: always
    shm_size: 500m
    ports:
      - "127.0.0.1:${EXPOSE_SELENIUM:-4444}:4444"
    privileged: true
    env_file:
      - ${DOCKER_ENV_FILE:-.env}
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    profiles:
      - runners

  #####  STARTERS  #####

  migrations:
    restart: "no"
    build: .
    volumes:
      - type: "bind"
        source: "./alembic.ini"
        target: "/app/alembic.ini"
        read_only: true
      - type: "bind"
        source: "./config/"
        target: "/app/config/"
        read_only: true
    entrypoint: [ "poetry", "run", "alembic", "upgrade", "heads" ]
    depends_on:
      - postgres
    profiles:
      - starters
      - migrations

volumes:
  redis:
  postgres:
  rabbitmq: