"""empty message

Revision ID: 31aac88ebed0
Revises: 43cf494af335
Create Date: 2023-10-27 17:15:02.816272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31aac88ebed0'
down_revision: Union[str, None] = '43cf494af335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birthdays', sa.Column('uuid', sa.UUID(), nullable=False))
    op.alter_column('birthdays', 'post',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('birthdays', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birthdays', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('birthdays', 'post',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('birthdays', 'uuid')
    # ### end Alembic commands ###
