"""empty message

Revision ID: b96de075639e
Revises: 12b9cac0f2a4
Create Date: 2023-10-12 12:56:44.597372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96de075639e'
down_revision: Union[str, None] = '12b9cac0f2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
